"""
Build the local search index from the corpus (data/corpus.jsonl).

Runs entirely offline once the embedding model is cached. Output is two small
files in data/index/ -- a numpy array of vectors plus the chunk
metadata, so there's no database to install or run.

Re-run this (python build_index.py) after any re-scrape that regenerates the
corpus, e.g. after the change-watch script finds changes.
"""
import json
import pathlib

import numpy as np

from . import config


def load_corpus(path=None) -> list[dict]:
    path = pathlib.Path(path) if path else config.CORPUS
    if not path.exists():
        raise SystemExit(
            f"Corpus not found: {path}\n"
            "Run pipeline/build_corpus.py first."
        )
    with open(path, encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def embed_text(chunk: dict) -> str:
    """What we actually embed -- CONTEXTUAL RETRIEVAL.

    A chunk is embedded together with a short, deterministic description of
    where it sits, not just its own body. Many chunks are bare list items or a
    tail of a long section, and on their own they carry almost none of the
    subject they belong to: a fragment reading "up to a maximum of RM160.00 per
    day" is, as an embedding, about numbers rather than about refugee medical
    insurance.

    The context line is built from metadata the corpus already carries, NOT
    generated by a model. That keeps the index build offline and instant, and
    -- far more important here -- it cannot invent a detail. An LLM-written
    context sentence is one more place a wrong fee or eligibility rule could be
    introduced, and this archive's whole safety argument is that nothing in the
    retrieval path is imagined.

    Repeating the title/heading is deliberate: it thickens the topical signal
    for the many chunks whose body text is mostly names, numbers or addresses.
    """
    title = chunk["doc_title"]
    heading = chunk.get("section_heading")

    where = f"{title} > {heading}" if heading else title
    context = f"This is part of the UNHCR Malaysia guidance page: {where}."

    parts = [where, context]
    if heading:
        parts.append(heading)
    parts.append(chunk["text"])
    return "\n".join(parts)


def build(out_dir=None, corpus=None, progress=None) -> None:
    """Build the index.

    `out_dir` writes somewhere other than data/index/. The refresh pipeline
    uses that to build into a staging directory and swap it in atomically once
    a human has read the diff -- because build() overwrites the two index files
    in place, and the desktop app may be reading them at that moment. A case
    worker mid-question should never see a half-written index.

    `progress(stage, done, total)` reports the same steps this function prints,
    for callers with no console to print to. The desktop app builds the index
    from a button on the splash (pakpatat/firstrun.py) and a build with no visible
    progress is indistinguishable from a hang -- this one takes minutes.
    """
    from fastembed import TextEmbedding

    def _say(stage, done=None, total=None):
        if progress:
            progress(stage, done, total)

    chunks = load_corpus(corpus)
    src = pathlib.Path(corpus) if corpus else config.CORPUS
    print(f"Loaded {len(chunks)} chunks from {src.name}")
    _say("reading", 0, len(chunks))

    out_dir = pathlib.Path(out_dir) if out_dir else config.INDEX_DIR
    out_vectors = out_dir / "vectors.npy"
    out_meta = out_dir / "meta.json"

    print(f"Loading embedding model ({config.EMBED_MODEL})...")
    print("  First run downloads ~220MB; after that it works fully offline.")
    _say("model", None, None)
    model = TextEmbedding(config.EMBED_MODEL)

    texts = [embed_text(c) for c in chunks]
    print("Embedding (this takes a minute on first run)...")
    # Consumed one at a time rather than list(...) so the caller can be told how
    # far along it is. Same result, same order -- embed() is a generator.
    rows = []
    for i, vec in enumerate(model.embed(texts), 1):
        rows.append(vec)
        if i % 25 == 0 or i == len(texts):
            _say("embedding", i, len(texts))
    vectors = np.array(rows, dtype=np.float32)
    # Pre-normalise so cosine similarity is a plain dot product at query time.
    vectors /= np.linalg.norm(vectors, axis=1, keepdims=True)
    _say("writing", None, None)

    out_dir.mkdir(parents=True, exist_ok=True)
    np.save(out_vectors, vectors)

    # Keep only the fields the assistant needs at answer time; drop the rest so
    # the metadata file stays small and fast to load.
    meta = [
        {
            "chunk_id": c["chunk_id"],
            "source": c["source"],
            "doc_title": c["doc_title"],
            "section_heading": c.get("section_heading"),
            "url": c["url"],
            "status": c["status"],
            "currency_note": c["currency_note"],
            "doc_path": c["doc_path"],
            "text": c["text"],
            # Carried through so the answer can name the document it came from.
            # Dropping it here would leave the citation stranded in the corpus,
            # invisible to retrieval and therefore to the reader.
            **({"citation": c["citation"]} if c.get("citation") else {}),
            **({"source_document": c["source_document"]}
               if c.get("source_document") else {}),
            **({"review_by": c["review_by"]} if c.get("review_by") else {}),
        }
        for c in chunks
    ]
    out_meta.write_text(
        json.dumps({"embed_model": config.EMBED_MODEL, "chunks": meta},
                   ensure_ascii=False),
        encoding="utf-8",
    )

    print(f"\nIndex built: {vectors.shape[0]} chunks x {vectors.shape[1]} dims")
    print(f"  -> {out_vectors}")
    print(f"  -> {out_meta}")


if __name__ == "__main__":
    build()
