#!/usr/bin/env python3
"""
Generate the Windows VERSIONINFO resource from pakpatat.__version__.

The version has to appear in four places on Windows -- the .exe's Properties
tab, the installer filename, the Add/Remove Programs entry, and the upgrade
check that decides whether an install replaces or duplicates the last one. If
those are typed separately they drift, and a user ends up with two "Pakpatat"
entries in Add/Remove Programs that are different builds.

So `pakpatat/__init__.py` is the single source and everything else is generated:

    python packaging/version_info.py            # writes packaging/version_info.txt
    python packaging/version_info.py --print    # just echo the version (for CI)
"""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from pakpatat import __version__ as VERSION      # noqa: E402
from pakpatat import brand                       # noqa: E402

TEMPLATE = """\
# Generated by packaging/version_info.py -- do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({v0}, {v1}, {v2}, 0),
    prodvers=({v0}, {v1}, {v2}, 0),
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', '{company}'),
         StringStruct('FileDescription', '{description}'),
         StringStruct('FileVersion', '{version}'),
         StringStruct('InternalName', '{slug}'),
         StringStruct('OriginalFilename', '{slug}.exe'),
         StringStruct('ProductName', '{product}'),
         StringStruct('ProductVersion', '{version}'),
         StringStruct('LegalCopyright', '{copyright}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def parts(version: str) -> tuple[int, int, int]:
    m = re.match(r"^(\d+)\.(\d+)\.(\d+)", version)
    if not m:
        raise SystemExit(f"__version__ must start with X.Y.Z, got {version!r}")
    return tuple(int(g) for g in m.groups())               # type: ignore[return-value]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--print", action="store_true", help="echo the version and exit")
    args = ap.parse_args()
    if args.print:
        print(VERSION)
        return

    v0, v1, v2 = parts(VERSION)
    out = ROOT / "packaging" / "version_info.txt"
    out.write_text(TEMPLATE.format(
        v0=v0, v1=v1, v2=v2, version=VERSION,
        product=brand.NAME_ASCII,           # ASCII: the resource table is cp1252
        slug=brand.SLUG,
        company="Independent community tool - not affiliated with UNHCR",
        description="Offline cited answers for refugee case workers",
        copyright="MIT licensed. Ships no archive content - see NOTICE.md",
    ), encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} for version {VERSION}")


if __name__ == "__main__":
    main()
